### ISSUE TITLE
file create error

### ISSUE THREAD

**Issue by codeMonkey-shin** [EtiennePerot/safe-code-execution#16]
If you try to create and download a file with Python code,
{"detail":"Not Found"}

is output.

When you actually connect to the container and enter that path, no files exist.

It seems that all files are probably deleted after the code is executed.

**Comment by EtiennePerot** [comment]
Perhaps you need to tweak the "Web Accessible Directory Path" and "Web Accessible Directory Url" valves? If you run Open WebUI with a custom image or behind a reverse proxy or similar, you need to edit those. The "Web Accessible Directory Path" valve needs to point to the storage directory within the container that output files should be stored in, and "Web Accessible Directory Url" corresponds to the URL prefix that points to that directory.

> It seems that all files are probably deleted after the code is executed.

No, all the files listed in the output files are retained (so long as the user has quota, as per the "Max Files Per User" and "Max Megabytes Per User" valves).

**Comment by codeMonkey-shin** [comment]
I used the official openwebui image in Kubernetes to deploy it externally. also 
"Web Accessible Directory Path" and "Web Accessible Directory Url" 
was set as default.

**Comment by EtiennePerot** [comment]
OK. Can you try it manually? If you `kubectl exec` into the Open WebUI container, and inspect the files in the Web Accessible Directory Path (default `/data/cache/functions/run_code`), is any file or directory there?

If you create a file in this directory (`echo hello world > /data/cache/functions/run_code/hello.txt`), can you access it by URL? (Default would be `http://openwebuihost:port/cache/functions/run_code/hello.txt`)

**Comment by codeMonkey-shin** [comment]
I use the open-webui official image. My open-webui directory actually exists in /app/backend .

because 
It works by changing the Web Accessible Directory Path to /app/backend/data/cache/functions/run_code.

**Comment by EtiennePerot** [comment]
Curious, I don't know why I'm not hitting this. I am using a custom image but not sure why it would change this behavior.
Re-opening this issue to track and verify whether the default "Web Accessible Directory Path" should be changed.

**Comment by codeMonkey-shin** [comment]
Is there anything I can do to help?

**Comment by EtiennePerot** [comment]
Yes. I think I figured it out, but not sure if the fix works so you can test it. Try the function after commit https://github.com/EtiennePerot/safe-code-execution/commit/8e435ef653e64130e873c58f78d804a288639ef9.

**Comment by phpia** [comment]
hello is necessary any special prompt for allow download files?

thanks

**Comment by EtiennePerot** [comment]
@phpia No special prompt necessary. The code execution function will display any file that is created in the script's current working directory (which appears as `/home/user` inside the sandbox).

**Comment by EtiennePerot** [comment]
Tool mode is for the LLM to reason and run its own code, so any output or files generated during that process should be irrelevant to the user, hence why the files are not preserved in tool mode. Is there a use case you have in mind where they would be useful to keep around?

**Comment by phpia** [comment]
I think that is more usable for regular user since its no necessary to click on the run code button.

Attach two images one for chatgpt and another from your great function :)
![Captura desde 2024-10-08 11-51-12](https://github.com/user-attachments/assets/45e89261-0903-4170-871b-24729d7ca6db)
![Captura desde 2024-10-08 11-53-06](https://github.com/user-attachments/assets/893f0dde-7f58-454c-8e40-33bdfa30087f)
