### ISSUE TITLE
Function to select when there are multiple code blocks

### ISSUE THREAD

**Issue by codeMonkey-shin** [EtiennePerot/safe-code-execution#24]
When you tell it to write code that uses an external library, chatgpt often even writes a pip install command. At this time, when you run the code, the pip install command is executed, not the Python code. Also, if multiple python codes are output, code execution becomes confusing. Therefore, it seems necessary to have a function that allows the user to select and execute a specific code block.

**Comment by EtiennePerot** [comment]
I agree, but closing as this issue is a duplicate of issue #15.
