### ISSUE TITLE
Folding code execution effect message block

### ISSUE THREAD

**Issue by EntropyYue** [EtiennePerot/safe-code-execution#25]
UI supports the following syntax in the dev version. After the official update, I will submit a PR as shown in the title.

<details>
<summary>Code Execution</summary>
I executed the following Python code: 
```python
print(helloworld)
```
```output
helloworld
```
</details>

**Comment by EtiennePerot** [comment]
That would be cool. If the code can be shown as part of the message itself, rather than as a citation, then it can be rendered as a code block and with proper syntax highlighting.

**Comment by xiaopa233** [comment]
I'm sorry I don't quite understand the content in the Development guide. Could you please explain which file changes I should submit?

**Comment by EtiennePerot** [comment]
You should modify the files in `/src`, then run the script at `/build/build_openwebui.py` (this will update the files in `/open-webui`), and then commit everything.

**Comment by EtiennePerot** [comment]
I just committed a bunch of changes, so you may have to merge them with yours. Sorry, I hope this is OK.

**Comment by xiaopa233** [comment]
My changes are very minor; there is no difficulty in merging them

**Comment by EtiennePerot** [comment]
Fixed by #28
