### ISSUE TITLE
[DOC update] Add some doc on how to add libraires to gVisor

### ISSUE THREAD

**Issue by nekopep** [EtiennePerot/safe-code-execution#30]
## Description

Hi etienne, just a quick feedback on this fontastic tool :)
I managed to execute a ping command from my openweb-ui chat and also make it run a matplotlib code.

I think you should add some doc on these two use cases:

1/adding tools to gVisor context:
In the docker file add needed tools:
**RUN apt-get install -y iputils-ping sudo**
After that it works (if you enable network access in sandbox)
![image](https://github.com/user-attachments/assets/261168f7-3f8a-4071-abf6-91425456f50e)

2/adding more python libs:
Strangely adding python3-xxx package did not worked as expected; your tool still didn't find the libs:
**RUN apt-get install -y python3-numpy python3-matplotlib**
but this works:
**RUN pip install matplotlib numpy**
Which is better by the way :)

Still I can't manage to get result from matplolib, I need to run proposed code to get an image, is this expected?
![image](https://github.com/user-attachments/assets/41ca389a-58bd-436d-8abc-0cbd2d137b70)

3/Any way to support venv? For example is it possible to prepare some venv and to propose to the tool to use this ot this venv?

Thanks!

## General information

- **Open WebUI version**: v0.3.32
- **Tool/function version**: 0.8.0
- **Open WebUI setup**:
  - **Kernel information**: 6.10.11+bpo-amd64
  - **Runtime**: doker-compose
  - If running in Docker:
    - **Docker version**: Docker version 27.3.1, build ce12230

**Comment by EtiennePerot** [comment]
I will add documentation to mention that you can preinstall tools and packages, but per issue #15 I think the better end state here is to allow sandboxes to install their own command-line tools and Python packages. Installing Debian and Python packages from inside the sandbox is safer, it can accommodate multi-user setups, and it doesn't require users to modify their `Dockerfile`. For this same reason, supporting venv is not needed; it would just become code that isn't needed once each sandbox can install its own packages.

And yes, `matplotlib` not displaying images is a known issue. The code execution function however display any image inline that is saved to disk.
