### ISSUE TITLE
Add ability to view code executed by tool

### ISSUE THREAD

**Issue by lu4p** [EtiennePerot/safe-code-execution#8]
In order to trust/ verify the output it's often useful to see what code has been executed.

How this works in ChatGPT:

![Screenshot from 2024-09-10 23-08-47](https://github.com/user-attachments/assets/ecb2cd32-5192-4792-9534-563a12f75935)
![Screenshot from 2024-09-10 23-09-06](https://github.com/user-attachments/assets/1f29ec2c-d082-4c0d-b756-d395259cd57a)

**Comment by EtiennePerot** [comment]
This is a good idea. Need Open WebUI support for this though. Currently tools cannot emit messages that would show up in this manner. I'm not very familiar with the way Open WebUI's UI framework works, but I think the right thing to place to start is to modify [this file](https://github.com/open-webui/open-webui/blob/main/src/lib/components/chat/Messages/ResponseMessage.svelte) and expand the `MessageType` to be able to attach this information, then change the rendering code below to display it.

**Comment by xiaopa233** [comment]
> This is a good idea. Need Open WebUI support for this though. Currently tools cannot emit messages that would show up in this manner. I'm not very familiar with the way Open WebUI's UI framework works, but I think the right thing to place to start is to modify [this file](https://github.com/open-webui/open-webui/blob/main/src/lib/components/chat/Messages/ResponseMessage.svelte) and expand the `MessageType` interface therein in order to be able to attach this information, then change the rendering code below to display it.

I think that it's a good idea to display the code in the citation

**Comment by xiaopa233** [comment]
I proposed a PR that displays the executed code in a citation #23

**Comment by EtiennePerot** [comment]
I have sent https://github.com/open-webui/open-webui/pull/5955 as an upstream PR to Open WebUI to add UI elements specifically for displaying code execution status.

**Comment by EtiennePerot** [comment]
This is implemented as of 0f297978a1855b827d96ba8fe295d7b006b44877.
